import { IRunewordGrailApiData } from "../definitions/api/IRunewordGrailApiData";

export const runewordGrailSeedData: IRunewordGrailApiData = {
  "Ancient's Pledge": {},
  Beast: {},
  Black: {},
  Bone: {},
  Bramble: {},
  Brand: {},
  "Breath of the Dying": {},
  "Call to Arms": {},
  "Chains of Honor": {},
  Chaos: {},
  "Crescent Moon": {},
  Death: {},
  Delirium: {},
  Destruction: {},
  Doom: {},
  Dragon: {},
  Dream: {},
  Duress: {},
  Edge: {},
  Enigma: {},
  Enlightenment: {},
  Eternity: {},
  Exile: {},
  Faith: {},
  Famine: {},
  Fortitude: {},
  Fury: {},
  Gloom: {},
  Grief: {},
  "Hand of Justice": {},
  Harmony: {},
  "Heart of the Oak": {},
  "Holy Thunder": {},
  Honor: {},
  Ice: {},
  Infinity: {},
  Insight: {},
  "King's Grace": {},
  Kingslayer: {},
  "Last Wish": {},
  Lawbringer: {},
  Leaf: {},
  Lionheart: {},
  Lore: {},
  Malice: {},
  Melody: {},
  Memory: {},
  Myth: {},
  Nadir: {},
  Oath: {},
  Obedience: {},
  Passion: {},
  Peace: {},
  Phoenix: {},
  Pride: {},
  Principle: {},
  Prudence: {},
  Radiance: {},
  Rain: {},
  Rhyme: {},
  Rift: {},
  Sanctuary: {},
  Silence: {},
  Smoke: {},
  Spirit: {},
  Splendor: {},
  Stealth: {},
  Steel: {},
  Stone: {},
  Strength: {},
  Treachery: {},
  Venom: {},
  "Voice of Reason": {},
  Wealth: {},
  White: {},
  Wind: {},
  Wrath: {},
  Zephyr: {}
};
