export const ItemScores = {
  "Nokozan Relic": 1,
  "Gheed's Fortune": 1,
  Nagelring: 1,
  "Manald Heal": 1,
  "Angelic Halo": 1,
  "Cathan's Seal": 1,
  Goreshovel: 1,
  "Rogue's Bow": 1,
  Steelgoad: 1,
  Gleamscythe: 1,
  Shadowfang: 1,
  "Angelic Mantle": 1,
  "Berserker's Headgear": 1,
  "Civerb's Ward": 1,
  "Cleglaw's Pincers": 1,
  "Hsarus' Iron Stay": 1,
  "Hsarus' Iron Heel": 1,
  Duskdeep: 1,
  Hawkmail: 1,
  "Sparking Mail": 1,
  Steelclash: 1,
  Bladebone: 1,
  Ichorsting: 1,
  Bloodrise: 1,
  "Soul Harvest": 1,
  "Griswold's Edge": 1,
  "Berserker's Hatchet": 1,
  "Cathan's Mesh": 1,
  "Civerb's Cudgel": 1,
  "Isenhart's Lightbrand": 1,
  "Isenhart's Horns": 1,
  "Milabrega's Orb": 1,
  "Venom Ward": 1,
  "The Chieftain": 1,
  Stormstrike: 1,
  "The Jade Tan Do": 1,
  Bloodthief: 1,
  Soulflay: 1,
  "Cathan's Rule": 1,
  "Isenhart's Case": 1,
  "Sander's Superstition": 1,
  "Skull Splitter": 1,
  "The General's Tan Do Li Ga": 1,
  Bonesnap: 1,
  "The Battlebranch": 1,
  "Lance of Yaggai": 1,
  Hellplague: 1,
  "Kinemil's Awl": 1,
  "Arctic Mitts": 1,
  "Berserker's Hauberk": 1,
  "Cathan's Visage": 1,
  "Cleglaw's Tooth": 1,
  "Infernal Sign": 1,
  "Iratha's Cord": 1,
  "Iratha's Cuff": 1,
  "Milabrega's Rod": 1,
  "Tancred's Crowbill": 1,
  "Vidala's Fetlock": 1,
  Brainhew: 1,
  Wizendraw: 1,
  "Spectral Shard": 1,
  "Sigon's Visor": 1,
  "Sigon's Guard": 1,
  "Tancred's Skull": 1,
  "Vidala's Barb": 1,
  "Naj's Circlet": 1,
  Frostburn: 1,
  Tearhaunch: 1,
  Bladebuckle: 1,
  "Arctic Horn": 1,
  "Death's Touch": 1,
  "Sigon's Sabot": 1,
  "Sigon's Wrap": 1,
  "Sigon's Gage": 1,
  "Arctic Furs": 1,
  "Death's Hand": 1,
  "Death's Guard": 1,
  "Hsarus' Iron Fist": 1,
  "Infernal Cranium": 1,
  "Tancred's Hobnails": 1,
  "Vidala's Ambush": 1,
  "Sander's Paragon": 1,
  "Iratha's Coil": 1,
  "Isenhart's Parry": 1,
  "Milabrega's Diadem": 1,
  "Sigon's Shelter": 1,
  "Arcanna's Flesh": 1,
  "Cow King's Horns": 1,
  "Rite of Passage": 1,
  "Aldur's Rhythm": 1,
  "Hwanin's Justice": 1,
  "Haemosu's Adamant": 1,
  "Tal Rasha's Horadric Crest": 1,
  Tarnhelm: 1,
  "The Centurion": 1,
  "Umbral Disk": 1,
  "Axe of Fechmar": 1,
  Leadcrow: 1,
  Stoutnail: 1,
  "Dimoak's Hew": 1,
  "The Dragon Chang": 1,
  "Blood Crescent": 1,
  "Arcanna's Head": 1,
  "Cleglaw's Claw": 1,
  "Immortal King's Stone Crusher": 1,
  Bloodfist: 1,
  Gorefoot: 1,
  Deathspade: 1,
  Crushflange: 1,
  "Serpent Lord": 1,
  "Angelic Sickle": 1,
  "Arctic Binding": 1,
  "Cow King's Hide": 1,
  "Cow King's Hooves": 1,
  "Sander's Taboo": 1,
  "Sander's Riprap": 1,
  "The Mahim-Oak Curio": 2,
  "Angelic Wings": 2,
  "Cathan's Sigil": 2,
  "Civerb's Icon": 2,
  "Iratha's Collar": 2,
  "Tancred's Weird": 2,
  "Vidala's Snare": 2,
  Annihilus: 2,
  "Hellfire Torch": 2,
  "Dwarf Star": 2,
  "Raven Frost": 2,
  "Coif of Glory": 2,
  Darkglow: 2,
  Stormguild: 2,
  "Swordback Hold": 2,
  "Chance Guards": 2,
  "Treads of Cthon": 2,
  Nightsmoke: 2,
  "Hwanin's Blessing": 2,
  "The Face of Horror": 2,
  Iceblink: 2,
  "Wall of the Eyeless": 2,
  Magefist: 2,
  "Goblin Toe": 2,
  Goldwrap: 2,
  Howltusk: 2,
  Wormskull: 2,
  Boneflesh: 2,
  "Bverrit Keep": 2,
  Hellcast: 2,
  "The Tannr Gorerod": 2,
  Blacktongue: 2,
  "Arcanna's Deathwand": 2,
  Rakescar: 2,
  Humongous: 2,
  Hellclap: 2,
  Ironstone: 2,
  "Culwen's Point": 2,
  Ripsaw: 2,
  "Infernal Torch": 2,
  "Biggin's Bonnet": 2,
  "Pelta Lunata": 2,
  "The Hand of Broc": 2,
  Hotspur: 2,
  "The Gnasher": 2,
  Gull: 2,
  Felloak: 2,
  "Rixot's Keen": 2,
  "Undead Crown": 2,
  Rockfleece: 2,
  "The Ward": 2,
  Skystrike: 2,
  "Dark Clan Crusher": 2,
  Woestave: 2,
  Bloodletter: 2,
  Rattlecage: 2,
  "Venom Grip": 2,
  Coldkill: 2,
  Blastbark: 2,
  Riphook: 2,
  Doomslinger: 2,
  Spineripper: 2,
  Steeldriver: 2,
  Fleshrender: 2,
  "The Meat Scraper": 2,
  "The Impaler": 2,
  "The Patriarch": 2,
  "Butcher's Pupil": 2,
  "Warlord's Trust": 2,
  "Kuko Shakaku": 2,
  "Langer Briser": 2,
  "Heart Carver": 2,
  "Sureshrill Frost": 2,
  "The Grim Reaper": 2,
  "Kelpie Snare": 2,
  Hexfire: 2,
  "Tancred's Spine": 2,
  "M'avina's Tenet": 2,
  "Whitstan's Guard": 2,
  "Magnus' Skin": 2,
  "Laying of Hands": 2,
  "Hwanin's Splendor": 2,
  "Dangoon's Teaching": 2,
  "Dark Adherent": 2,
  "Griswold's Heart": 2,
  Twitchthroe: 2,
  Snakecord: 2,
  "Raven Claw": 2,
  "The Diggler": 2,
  Razortine: 2,
  "Skewer of Krintiz": 2,
  Rusthandle: 3,
  "The Salamander": 3,
  Gravenspine: 3,
  Stormeye: 3,
  "Immortal King's Will": 3,
  Deathbit: 3,
  "Peasant Crown": 3,
  "Heavenly Garb": 3,
  "The Spirit Shroud": 3,
  "Skin of the Vipermagi": 3,
  Visceratuant: 3,
  Infernostride: 3,
  "String of Ears": 3,
  "Pierre Tombale Couant": 3,
  "The Scalper": 3,
  Spellsteel: 3,
  Endlesshail: 3,
  "Blade of Ali Baba": 3,
  "Ginther's Rift": 3,
  "Milabrega's Robe": 3,
  "Hwanin's Refuge": 3,
  "Natalya's Soul": 3,
  "Sazabi's Mental Sheath": 3,
  "Tal Rasha's Fine Spun Cloth": 3,
  "Trang-Oul's Claws": 3,
  "Blackhorn's Face": 3,
  "Duriel's Shell": 3,
  "Lidless Wall": 3,
  "Immortal King's Detail": 3,
  "Immortal King's Forge": 3,
  "Immortal King's Pillar": 3,
  "Demon Limb": 3,
  "Grim's Burning Dead": 3,
  Wizardspike: 3,
  Bonehew: 3,
  "Arioc's Needle": 3,
  "Trang-Oul's Scales": 3,
  "Spire of Lazarus": 4,
  Maelstrom: 4,
  "The Iron Jang Bong": 4,
  Greyform: 4,
  "Blinkbat's Form": 4,
  Lenymo: 4,
  Pluckeye: 4,
  Islestrike: 4,
  Moonfall: 4,
  "Blackleach Blade": 4,
  "Crainte Vomir": 4,
  "Pompeii's Wrath": 4,
  "Witchwild String": 4,
  "Baezil's Vortex": 4,
  "Bloodtree Stump": 4,
  "Hone Sundan": 4,
  "Coldsteel Eye": 4,
  "Plague Bearer": 4,
  "The Vile Husk": 4,
  "Guardian Naga": 4,
  "Boneslayer Blade": 4,
  Cliffkiller: 4,
  "Buriza-Do Kyanon": 4,
  Stormspike: 4,
  Earthshaker: 4,
  "Spire of Honor": 4,
  Cloudcrack: 4,
  "The Minotaur": 4,
  Magewrath: 4,
  "Husoldal Evo": 4,
  "The Atlantean": 4,
  "Todesfaelle Flamme": 4,
  "Bartuc's Cut-Throat": 4,
  "Aldur's Advance": 4,
  "M'avina's Icy Clutch": 4,
  "Natalya's Totem": 4,
  "Guillaume's Face": 4,
  "Wilhelm's Pride": 4,
  "Razor's Edge": 4,
  "Goldstrike Arch": 4,
  "Demon Machine": 4,
  "The Gavel of Pain": 4,
  Swordguard: 4,
  "Crown of Thieves": 4,
  Toothrow: 4,
  "Radament's Sphere": 4,
  Gimmershred: 4,
  Witherstring: 4,
  "Djinn Slayer": 4,
  Bloodmoon: 4,
  "Jade Talon": 4,
  "Ethereal Edge": 4,
  Windhammer: 4,
  Credendum: 4,
  "Natalya's Shadow": 4,
  "The Eye of Etlich": 5,
  "Ume's Lament": 5,
  Razorswitch: 5,
  "Titan's Revenge": 5,
  Rockstopper: 5,
  Goldskin: 5,
  "Skin of the Flayed One": 5,
  "Moser's Blessed Circle": 5,
  Gravepalm: 5,
  Waterwalk: 5,
  Razortail: 5,
  Stormrider: 5,
  "Pus Spitter": 5,
  "Blackbog's Sharp": 5,
  "Athena's Wrath": 5,
  "Soulfeast Tine": 5,
  Headstriker: 5,
  "Bing Sz Wang": 5,
  "Aldur's Stony Gaze": 5,
  "Nord's Tenderizer": 5,
  "Harlequin Crest": 5,
  "Que-Hegan's Wisdom": 5,
  "Atma's Wail": 5,
  "Carrion Wind": 6,
  "Knell Striker": 6,
  "Bane Ash": 6,
  "Torch of Iro": 6,
  Stealskull: 6,
  "Silks of the Victor": 6,
  "Iron Pelt": 6,
  "Spirit Forge": 6,
  Stormchaser: 6,
  "Lance Guard": 6,
  "Guardian Angel": 6,
  Hellmouth: 6,
  "Gore Rider": 6,
  "Thundergod's Vigor": 6,
  Corpsemourn: 6,
  "Ormus' Robes": 6,
  "Sandstorm Trek": 6,
  "Rune Master": 6,
  "Demon's Arch": 6,
  "Baranar's Star": 6,
  "The Reaper's Toll": 6,
  Flamebellow: 6,
  "Shadow Killer": 6,
  "Zakarum's Hand": 7,
  "Suicide Branch": 7,
  Ribcracker: 7,
  "Darksight Helm": 7,
  "Crow Caw": 7,
  Shaftstop: 7,
  "Tiamat's Rebuke": 7,
  Ghoulhide: 7,
  Silkweave: 7,
  "Gloom's Trap": 7,
  "Tal Rasha's Lidless Eye": 7,
  "Jalal's Mane": 7,
  Thunderstroke: 7,
  "Eschuta's Temper": 7,
  Hellslayer: 7,
  Hellrack: 7,
  Viperfork: 7,
  "Saracen's Chance": 8,
  "The Cat's Eye": 8,
  "Crescent Moon": 8,
  "Atma's Scarab": 8,
  "The Rising Sun": 8,
  "Highlord's Wrath": 8,
  "Lycander's Aim": 8,
  "Lycander's Flank": 8,
  "The Oculus": 8,
  "Black Hades": 8,
  "Blackoak Shield": 8,
  "Dracul's Grasp": 8,
  "Arachnid Mesh": 8,
  Stoneraven: 8,
  "Kira's Guardian": 8,
  "The Gladiator's Bane": 8,
  Lightsabre: 8,
  "Naj's Puzzler": 8,
  "Valkyrie Wing": 9,
  "Vampire Gaze": 9,
  "Skullder's Ire": 9,
  "Gerke's Sanctuary": 9,
  "Lava Gout": 9,
  "War Traveler": 9,
  Snowclash: 9,
  "Blood Raven's Charge": 9,
  Stormshield: 9,
  Marrowwalk: 9,
  "Stone of Jordan": 10,
  "Chromatic Ire": 10,
  "Carin Shard": 10,
  Wolfhowl: 10,
  "Steel Shade": 10,
  "Spike Thorn": 10,
  "Soul Drainer": 10,
  "Nosferatu's Coil": 10,
  Homunculus: 12,
  "Arreat's Face": 12,
  "Andariel's Visage": 12,
  "Verdungo's Hearty Cord": 12,
  "Arcanna's Sign": 13,
  "Telling of Beads": 13,
  "Tal Rasha's Adjudication": 13,
  "Hand of Blessed Light": 13,
  "Arm of King Leoric": 13,
  "Skull Collector": 13,
  "Blackhand Key": 13,
  "Heaven's Light": 13,
  "Seraph's Hymn": 14,
  "Trang-Oul's Wing": 14,
  "The Fetid Sprinkler": 15,
  Warpspear: 15,
  "Cerebus' Bite": 15,
  "Alma Negra": 16,
  "Bul-Kathos' Wedding Band": 17,
  "Herald of Zakarum": 17,
  "Sazabi's Cobalt Redeemer": 17,
  "Nature's Peace": 19,
  "Naj's Light Plate": 19,
  "Sazabi's Ghost Liberator": 19,
  "Ondal's Almighty": 19,
  "M'avina's Embrace": 19,
  "Ondal's Wisdom": 21,
  Boneshade: 21,
  "Demonhorn's Edge": 21,
  "Mara's Kaleidoscope": 30,
  "Rainbow Facet": 30,
  "Rainbow Facet - Fire Level": 30,
  "Rainbow Facet - Fire Die": 30,
  "Rainbow Facet - Light Level": 30,
  "Rainbow Facet - Light Die": 30,
  "Rainbow Facet - Cold Level": 30,
  "Rainbow Facet - Cold Die": 30,
  "Rainbow Facet - Poison Level": 30,
  "Rainbow Facet - Poison Die": 30,
  "The Redeemer": 30,
  "Aldur's Deception": 30,
  "Taebaek's Glory": 30,
  "Tal Rasha's Guardianship": 30,
  "Trang-Oul's Guise": 30,
  "Trang-Oul's Girth": 30,
  "Firelizard's Talons": 35,
  "Bul-Kathos' Sacred Charge": 35,
  "Bul-Kathos' Tribal Guardian": 35,
  Azurewrath: 40,
  Eaglehorn: 40,
  Doombringer: 40,
  Warshrike: 40,
  Cranebeak: 40,
  Widowmaker: 40,
  "Wraith Flight": 40,
  "Tomb Reaver": 40,
  Lacerator: 40,
  "Griswold's Valor": 40,
  "Immortal King's Soul Cage": 40,
  "M'avina's True Sight": 40,
  "Horizon's Tornado": 45,
  "Arkaine's Valor": 50,
  "Head Hunter's Glory": 50,
  "M'avina's Caster": 50,
  "Medusa's Gaze": 50,
  "Natalya's Mark": 50,
  Leviathan: 55,
  "Messerschmidt's Reaver": 55,
  "Gut Siphon": 55,
  Fleshripper: 55,
  Frostwind: 55,
  "Wisp Projector": 60,
  "Stone Crusher": 70,
  Metalgrid: 75,
  "Spirit Keeper": 95,
  Boneflame: 95,
  "Halaberd's Reign": 95,
  "Giant Skull": 95,
  "Steel Carapace": 95,
  "Spirit Ward": 95,
  "Veil of Steel": 105,
  "Nightwing's Veil": 105,
  "Griswold's Redemption": 105,
  "Death Cleaver": 110,
  "Executioner's Justice": 110,
  Windforce: 110,
  Ghostflame: 110,
  "Gargoyle's Bite": 110,
  Stormspire: 110,
  "Steel Pillar": 110,
  "The Grandfather": 110,
  "Griswold's Honor": 120,
  "Crown of Ages": 130,
  "Griffon's Eye": 130,
  Steelrend: 130,
  "Shadow Dancer": 130,
  "Templar's Might": 135,
  Ravenlore: 175,
  Dragonscale: 175,
  "Death's Fathom": 200,
  "Earth Shifter": 220,
  "The Cranium Basher": 220,
  Stormlash: 230,
  "Darkforce Spawn": 230,
  "Schaefer's Hammer": 275,
  "Astreon's Iron Ward": 335,
  "Mang Song's Lesson": 335,
  "Death's Web": 335,
  "Tyrael's Might": 1155
};
