export const ItemScores = {
  "Nokozan Relic": 1,
  "Gheed's Fortune": 1,
  Annihilus: 1,
  Nagelring: 1,
  "Manald Heal": 1,
  "Angelic Halo": 1,
  "Cathan's Seal": 1,
  Goreshovel: 1,
  "Rogue's Bow": 1,
  Steelgoad: 1,
  Gleamscythe: 1,
  Shadowfang: 1,
  "Angelic Mantle": 1,
  "Berserker's Headgear": 1,
  "Civerb's Ward": 1,
  "Cleglaw's Pincers": 1,
  "Hsarus' Iron Stay": 1,
  "Hsarus' Iron Heel": 1,
  "Coif of Glory": 1,
  Darkglow: 1,
  Stormguild: 1,
  "Swordback Hold": 1,
  "Chance Guards": 1,
  "Treads of Cthon": 1,
  Nightsmoke: 1,
  "Hwanin's Blessing": 1,
  "Spire of Lazarus": 1,
  Maelstrom: 1,
  Duskdeep: 1,
  Hawkmail: 1,
  "Sparking Mail": 1,
  Steelclash: 1,
  Bladebone: 1,
  Ichorsting: 1,
  Bloodrise: 1,
  "Soul Harvest": 1,
  "Griswold's Edge": 1,
  "Berserker's Hatchet": 1,
  "Cathan's Mesh": 1,
  "Civerb's Cudgel": 1,
  "Isenhart's Lightbrand": 1,
  "Isenhart's Horns": 1,
  "Milabrega's Orb": 1,
  Rusthandle: 1,
  "Venom Ward": 1,
  "The Chieftain": 1,
  Stormstrike: 1,
  "The Jade Tan Do": 1,
  Bloodthief: 1,
  Soulflay: 1,
  "Cathan's Rule": 1,
  "Isenhart's Case": 1,
  "Sander's Superstition": 1,
  "The Salamander": 1,
  Gravenspine: 1,
  "Skull Splitter": 1,
  "The General's Tan Do Li Ga": 1,
  Bonesnap: 1,
  "The Battlebranch": 1,
  "Lance of Yaggai": 1,
  Hellplague: 1,
  "Kinemil's Awl": 1,
  "Arctic Mitts": 1,
  "Berserker's Hauberk": 1,
  "Cathan's Visage": 1,
  "Cleglaw's Tooth": 1,
  "Infernal Sign": 1,
  "Iratha's Cord": 1,
  "Iratha's Cuff": 1,
  "Milabrega's Rod": 1,
  "Tancred's Crowbill": 1,
  "Vidala's Fetlock": 1,
  "The Face of Horror": 1,
  Iceblink: 1,
  "Wall of the Eyeless": 1,
  Magefist: 1,
  "Goblin Toe": 1,
  Goldwrap: 1,
  Stormeye: 1,
  Brainhew: 1,
  Wizendraw: 1,
  Hellcast: 1,
  "Spectral Shard": 1,
  "The Tannr Gorerod": 1,
  Blacktongue: 1,
  "Sigon's Visor": 1,
  "Sigon's Guard": 1,
  "Tancred's Skull": 1,
  "Vidala's Barb": 1,
  "Naj's Circlet": 1,
  Howltusk: 1,
  Wormskull: 1,
  Boneflesh: 1,
  "Bverrit Keep": 1,
  "Arcanna's Deathwand": 1,
  "Immortal King's Will": 1,
  "The Iron Jang Bong": 1,
  Frostburn: 1,
  Tearhaunch: 1,
  Bladebuckle: 1,
  "Arctic Horn": 1,
  "Death's Touch": 1,
  "Sigon's Sabot": 1,
  "Sigon's Wrap": 1,
  "Sigon's Gage": 1,
  Rakescar: 1,
  Humongous: 1,
  Hellclap: 1,
  Ironstone: 1,
  "Culwen's Point": 1,
  Ripsaw: 1,
  "Infernal Torch": 1,
  "Ume's Lament": 1,
  "Umbral Disk": 1,
  "Axe of Fechmar": 1,
  Leadcrow: 1,
  Stoutnail: 1,
  "Dimoak's Hew": 1,
  "The Dragon Chang": 1,
  "Blood Crescent": 1,
  "Arcanna's Head": 1,
  "Cleglaw's Claw": 1,
  Tarnhelm: 1,
  "The Centurion": 1,
  Witherstring: 1,
  Bloodfist: 1,
  Gorefoot: 1,
  Deathspade: 1,
  Crushflange: 1,
  "Serpent Lord": 1,
  "Angelic Sickle": 1,
  "Arctic Binding": 1,
  "Cow King's Hide": 1,
  "Cow King's Hooves": 1,
  "Sander's Taboo": 1,
  "Sander's Riprap": 1,
  Twitchthroe: 1,
  Snakecord: 1,
  "Raven Claw": 1,
  "The Diggler": 1,
  Razortine: 1,
  "Skewer of Krintiz": 1,
  "The Mahim-Oak Curio": 2,
  "Angelic Wings": 2,
  "Cathan's Sigil": 2,
  "Civerb's Icon": 2,
  "Iratha's Collar": 2,
  "Tancred's Weird": 2,
  "Vidala's Snare": 2,
  "Dwarf Star": 2,
  "Raven Frost": 2,
  "Iratha's Coil": 2,
  "Isenhart's Parry": 2,
  "Milabrega's Diadem": 2,
  "Undead Crown": 2,
  Rockfleece: 2,
  "The Ward": 2,
  Skystrike: 2,
  "Dark Clan Crusher": 2,
  Woestave: 2,
  Bloodletter: 2,
  Razorswitch: 2,
  "Sigon's Shelter": 2,
  Rattlecage: 2,
  "Venom Grip": 2,
  Coldkill: 2,
  Blastbark: 2,
  Riphook: 2,
  Doomslinger: 2,
  Spineripper: 2,
  Steeldriver: 2,
  Fleshrender: 2,
  "The Meat Scraper": 2,
  "The Impaler": 2,
  "The Patriarch": 2,
  Deathbit: 2,
  "Zakarum's Hand": 2,
  "Suicide Branch": 2,
  "Arcanna's Flesh": 2,
  "Cow King's Horns": 2,
  "Rite of Passage": 2,
  "Butcher's Pupil": 2,
  "Warlord's Trust": 2,
  "Kuko Shakaku": 2,
  "Langer Briser": 2,
  "Heart Carver": 2,
  "Sureshrill Frost": 2,
  "The Grim Reaper": 2,
  "Kelpie Snare": 2,
  Hexfire: 2,
  "Peasant Crown": 2,
  "Heavenly Garb": 2,
  "The Spirit Shroud": 2,
  "Skin of the Vipermagi": 2,
  Visceratuant: 2,
  Infernostride: 2,
  "String of Ears": 2,
  "Pierre Tombale Couant": 2,
  "The Scalper": 2,
  "Titan's Revenge": 2,
  Ribcracker: 2,
  "Aldur's Rhythm": 2,
  "Hwanin's Justice": 2,
  "Tancred's Spine": 2,
  "M'avina's Tenet": 2,
  "Whitstan's Guard": 2,
  "Magnus' Skin": 2,
  Spellsteel: 2,
  Endlesshail: 2,
  "Blade of Ali Baba": 2,
  "Ginther's Rift": 2,
  Islestrike: 2,
  Moonfall: 2,
  "Blackleach Blade": 2,
  "Crainte Vomir": 2,
  Rockstopper: 2,
  Goldskin: 2,
  "Skin of the Flayed One": 2,
  "Moser's Blessed Circle": 2,
  Gravepalm: 2,
  Waterwalk: 2,
  Razortail: 2,
  "Arctic Furs": 4,
  "Death's Hand": 4,
  "Death's Guard": 4,
  "Hsarus' Iron Fist": 4,
  "Infernal Cranium": 4,
  "Tancred's Hobnails": 4,
  "Vidala's Ambush": 4,
  "Milabrega's Robe": 4,
  "The Eye of Etlich": 5,
  "Carrion Wind": 5,
  "Biggin's Bonnet": 5,
  "Pelta Lunata": 5,
  "The Hand of Broc": 5,
  Hotspur: 5,
  "The Gnasher": 5,
  Gull: 5,
  Felloak: 5,
  "Rixot's Keen": 5,
  "Sander's Paragon": 5,
  Pluckeye: 5,
  Greyform: 5,
  Stormrider: 5,
  "Pus Spitter": 5,
  "Blackbog's Sharp": 5,
  "Athena's Wrath": 5,
  "Soulfeast Tine": 5,
  Headstriker: 5,
  "Bing Sz Wang": 5,
  Stealskull: 5,
  "Silks of the Victor": 5,
  "Iron Pelt": 5,
  "Spirit Forge": 5,
  Stormchaser: 5,
  "Lance Guard": 5,
  "Hwanin's Refuge": 5,
  "Natalya's Soul": 5,
  "Sazabi's Mental Sheath": 5,
  "Tal Rasha's Fine Spun Cloth": 5,
  "Trang-Oul's Claws": 5,
  "Haemosu's Adamant": 5,
  "Tal Rasha's Horadric Crest": 5,
  "Pompeii's Wrath": 6,
  "Witchwild String": 6,
  "Baezil's Vortex": 6,
  "Bloodtree Stump": 6,
  "Hone Sundan": 6,
  "Coldsteel Eye": 6,
  "Plague Bearer": 6,
  "The Vile Husk": 6,
  "Darksight Helm": 6,
  "Crow Caw": 6,
  Shaftstop: 6,
  "Tiamat's Rebuke": 6,
  Ghoulhide: 6,
  Silkweave: 6,
  "Gloom's Trap": 6,
  "Blackhorn's Face": 6,
  "Duriel's Shell": 6,
  "Lidless Wall": 6,
  "Guardian Naga": 6,
  "Boneslayer Blade": 6,
  Cliffkiller: 6,
  "Buriza-Do Kyanon": 6,
  Stormspike: 6,
  Earthshaker: 6,
  "Spire of Honor": 6,
  Cloudcrack: 6,
  "Aldur's Stony Gaze": 6,
  "Aldur's Advance": 6,
  "M'avina's Icy Clutch": 6,
  "Natalya's Totem": 6,
  "Guillaume's Face": 6,
  "Wilhelm's Pride": 6,
  "Tal Rasha's Lidless Eye": 6,
  "Immortal King's Detail": 6,
  "Immortal King's Forge": 6,
  "Immortal King's Pillar": 6,
  "The Minotaur": 7,
  Magewrath: 7,
  "Husoldal Evo": 7,
  "The Atlantean": 7,
  "Todesfaelle Flamme": 7,
  "Bartuc's Cut-Throat": 7,
  "Lycander's Flank": 7,
  "The Oculus": 7,
  "Valkyrie Wing": 7,
  "Vampire Gaze": 7,
  "Skullder's Ire": 7,
  "Gerke's Sanctuary": 7,
  "Lava Gout": 7,
  "War Traveler": 7,
  Snowclash: 7,
  "Razor's Edge": 7,
  "Goldstrike Arch": 7,
  "Demon Machine": 7,
  "The Gavel of Pain": 7,
  Swordguard: 7,
  "Nord's Tenderizer": 7,
  "Guardian Angel": 7,
  Hellmouth: 7,
  "Gore Rider": 7,
  "Thundergod's Vigor": 7,
  "Blood Raven's Charge": 7,
  "Laying of Hands": 7,
  "Hwanin's Splendor": 7,
  "Dangoon's Teaching": 7,
  "Trang-Oul's Scales": 7,
  "Demon Limb": 8,
  "Grim's Burning Dead": 8,
  "Crown of Thieves": 8,
  Toothrow: 8,
  "Radament's Sphere": 8,
  Gimmershred: 8,
  "Jalal's Mane": 8,
  Wizardspike: 8,
  Bonehew: 8,
  "Arioc's Needle": 8,
  "Harlequin Crest": 8,
  "Que-Hegan's Wisdom": 8,
  "Atma's Wail": 8,
  "Djinn Slayer": 8,
  Bloodmoon: 8,
  "Jade Talon": 8,
  "Black Hades": 8,
  "Blackoak Shield": 8,
  "Dracul's Grasp": 8,
  "Arachnid Mesh": 8,
  Stoneraven: 8,
  "Dark Adherent": 8,
  "Griswold's Heart": 8,
  "Immortal King's Stone Crusher": 8,
  "Ethereal Edge": 9,
  Corpsemourn: 9,
  "Ormus' Robes": 9,
  "Sandstorm Trek": 9,
  Thunderstroke: 9,
  Windhammer: 9,
  "Eschuta's Temper": 9,
  "Rune Master": 9,
  "Demon's Arch": 9,
  "Baranar's Star": 9,
  "The Reaper's Toll": 9,
  Flamebellow: 9,
  "Kira's Guardian": 9,
  "The Gladiator's Bane": 9,
  Stormshield: 9,
  Marrowwalk: 9,
  Credendum: 9,
  "Natalya's Shadow": 9,
  "Saracen's Chance": 10,
  "The Cat's Eye": 10,
  "Crescent Moon": 10,
  "Atma's Scarab": 10,
  "The Rising Sun": 10,
  "Highlord's Wrath": 10,
  "Hellfire Torch": 10,
  "Rainbow Facet": 10,
  "Rainbow Facet - Fire Level": 10,
  "Rainbow Facet - Fire Die": 10,
  "Rainbow Facet - Light Level": 10,
  "Rainbow Facet - Light Die": 10,
  "Rainbow Facet - Cold Level": 10,
  "Rainbow Facet - Cold Die": 10,
  "Rainbow Facet - Poison Level": 10,
  "Rainbow Facet - Poison Die": 10,
  "Blinkbat's Form": 10,
  Lenymo: 10,
  "Knell Striker": 10,
  "Bane Ash": 10,
  "Torch of Iro": 10,
  "Chromatic Ire": 10,
  "Carin Shard": 10,
  "The Fetid Sprinkler": 10,
  Warpspear: 10,
  "Hand of Blessed Light": 10,
  "Arm of King Leoric": 10,
  "Lycander's Aim": 10,
  "Skull Collector": 10,
  "Blackhand Key": 10,
  "Trang-Oul's Wing": 10,
  Homunculus: 10,
  "Arreat's Face": 10,
  "Steel Shade": 10,
  "Spike Thorn": 10,
  "Soul Drainer": 10,
  "Nosferatu's Coil": 10,
  "Shadow Killer": 10,
  Hellslayer: 10,
  Hellrack: 10,
  Viperfork: 10,
  Lightsabre: 10,
  "Naj's Puzzler": 10,
  "Andariel's Visage": 10,
  "Verdungo's Hearty Cord": 10,
  "Arcanna's Sign": 15,
  "Telling of Beads": 15,
  "Tal Rasha's Adjudication": 15,
  "Stone of Jordan": 15,
  "Bul-Kathos' Wedding Band": 15,
  "Herald of Zakarum": 15,
  "Heaven's Light": 15,
  "Cerebus' Bite": 15,
  "The Redeemer": 15,
  Wolfhowl: 15,
  "Naj's Light Plate": 15,
  "Sazabi's Ghost Liberator": 15,
  "Alma Negra": 16,
  "Nature's Peace": 20,
  "Ondal's Wisdom": 20,
  Boneshade: 20,
  "Demonhorn's Edge": 20,
  "Ondal's Almighty": 20,
  "M'avina's Embrace": 20,
  "Seraph's Hymn": 25,
  "Mara's Kaleidoscope": 30,
  "Firelizard's Talons": 30,
  "Sazabi's Cobalt Redeemer": 30,
  "Aldur's Deception": 30,
  "Taebaek's Glory": 30,
  "Tal Rasha's Guardianship": 30,
  "Trang-Oul's Guise": 30,
  "Trang-Oul's Girth": 30,
  Azurewrath: 40,
  Eaglehorn: 40,
  Doombringer: 40,
  Warshrike: 40,
  Cranebeak: 40,
  Widowmaker: 40,
  "Wraith Flight": 40,
  "Tomb Reaver": 40,
  Lacerator: 40,
  "Horizon's Tornado": 50,
  "Arkaine's Valor": 50,
  "Head Hunter's Glory": 50,
  "M'avina's Caster": 50,
  "Medusa's Gaze": 50,
  "Messerschmidt's Reaver": 50,
  "Gut Siphon": 50,
  Fleshripper: 50,
  Frostwind: 50,
  "Stone Crusher": 50,
  "Bul-Kathos' Sacred Charge": 50,
  "Bul-Kathos' Tribal Guardian": 50,
  "Griswold's Valor": 50,
  "Immortal King's Soul Cage": 50,
  "M'avina's True Sight": 50,
  "Natalya's Mark": 50,
  Leviathan: 55,
  "Wisp Projector": 60,
  Metalgrid: 75,
  "Giant Skull": 75,
  "Steel Carapace": 75,
  "Spirit Ward": 75,
  "Spirit Keeper": 100,
  Boneflame: 100,
  "Halaberd's Reign": 100,
  "Veil of Steel": 100,
  "Nightwing's Veil": 100,
  "Griswold's Redemption": 125,
  "Death Cleaver": 125,
  "Executioner's Justice": 125,
  Windforce: 125,
  Ghostflame: 125,
  "Gargoyle's Bite": 125,
  Stormspire: 125,
  "Steel Pillar": 125,
  "The Grandfather": 125,
  "Griswold's Honor": 125,
  "Crown of Ages": 150,
  "Griffon's Eye": 150,
  Steelrend: 150,
  "Shadow Dancer": 150,
  "Earth Shifter": 150,
  "The Cranium Basher": 150,
  Ravenlore: 175,
  Dragonscale: 175,
  "Templar's Might": 175,
  "Death's Fathom": 200,
  "Darkforce Spawn": 200,
  Stormlash: 250,
  "Schaefer's Hammer": 250,
  "Astreon's Iron Ward": 350,
  "Mang Song's Lesson": 350,
  "Death's Web": 350,
  "Tyrael's Might": 1000
};

// fixes for old grail seed data
ItemScores["Crow Cow"] = ItemScores["Crow Caw"];
ItemScores["Chance Gaurds"] = ItemScores["Chance Guards"];
ItemScores["Shawdow Dancer"] = ItemScores["Shadow Dancer"];
ItemScores["The Chieftan"] = ItemScores["The Chieftain"];
ItemScores["General's Tan Do Li Ga"] = ItemScores["The General's Tan Do Li Ga"];
ItemScores["Baranar's Star "] = ItemScores["Baranar's Star"];
ItemScores["Demon Limb "] = ItemScores["Demon Limb"];
ItemScores["Stormlash "] = ItemScores.Stormlash;
ItemScores["Horizon's Tornado "] = ItemScores["Horizon's Tornado"];
ItemScores["Stone Crusher "] = ItemScores["Stone Crusher"];
ItemScores["Schaefer's Hammer "] = ItemScores["Schaefer's Hammer"];
ItemScores["Culwen's point"] = ItemScores["Culwen's Point"];
ItemScores["Wraith's Flight"] = ItemScores["Wraith Flight"];
ItemScores["Eye of Etlich"] = ItemScores["The Eye of Etlich"];
ItemScores["Mahim-Oak Curio"] = ItemScores["The Mahim-Oak Curio"];
ItemScores["Cat's Eye"] = ItemScores["The Cat's Eye"];
ItemScores["Rising Sun"] = ItemScores["The Rising Sun"];
ItemScores["Highlords Wrath"] = ItemScores["Highlord's Wrath"];
ItemScores["Bloodraven's Charge"] = ItemScores["Blood Raven's Charge"];
ItemScores["Sparkling Mail"] = ItemScores["Sparking Mail"];
(ItemScores as any).Viscerataunt = ItemScores.Visceratuant;
(ItemScores as any).Steelshade = ItemScores["Steel Shade"];

ItemScores["Tal Rasha's Fine-Spun Cloth"] =
  ItemScores["Tal Rasha's Fine Spun Cloth"];
ItemScores["Haemosu's Adament"] = ItemScores["Haemosu's Adamant"];
